### ISSUE TITLE
Windowsphone "at to start" missing Favicon

### ISSUE THREAD

**Issue by Elompenta** [martijnboland/moped#42]
On Windowsversion there is no favicon to display as APP Image if I Pin it to start

**Comment by martijnboland** [comment]
Is this issue fixed with the latest 0.6 version?

**Comment by Baebeca** [comment]
No Sorry - on Windows Phone Lumia 640 it is still Show a screenshot of my Playlist if i attach it to  the startscreen

**Comment by Baebeca** [comment]
If i found a Solution fir my Phone Modell i will create a fix

**Comment by Baebeca** [comment]
All your code and browserconfig seems correct
https://github.com/martijnboland/moped/blob/master/dist/assets/images/browserconfig.xml 

Is there any accesslog in your webserver?
So i can see what kind of image my phone try to load

Same code on own webserver works fine

**Comment by martijnboland** [comment]
With the decline of Windows Phone usage, this issue is probably not relevant anymore. Please reopen when otherwise.
